### ISSUE TITLE
`:class` dynamic attribute has some bugs when referencing props/attrs/data without `this`

### ISSUE THREAD

**Issue by zachleat** [11ty/webc#45]
Follow-up to #40.

```
[11ty] Original error stack trace: evalmachine.<anonymous>:1
[11ty] `toggle${class ? ` ${class}`: ''}`
[11ty]                ^
[11ty] 
[11ty] SyntaxError: Unexpected token '?'
[11ty]     at new Script (node:vm:100:7)
[11ty]     at createScript (node:vm:257:10)
[11ty]     at Object.runInNewContext (node:vm:298:10)
[11ty]     at Function.evaluateAttribute (file:///Users/zachleat/Code/webc/src/moduleScript.js:26:13)
[11ty]     at Function.normalizeAttribute (file:///Users/zachleat/Code/webc/src/attributeSerializer.js:67:39)
[11ty]     at Function.getString (file:///Users/zachleat/Code/webc/src/attributeSerializer.js:101:50)
[11ty]     at async AstSerializer.renderStartTag (file:///Users/zachleat/Code/webc/src/ast.js:646:30)
[11ty]     at async AstSerializer.compileNode (file:///Users/zachleat/Code/webc/src/ast.js:1051:45)
[11ty]     at async AstSerializer.getChildContent (file:///Users/zachleat/Code/webc/src/ast.js:544:29)
[11ty]     at async AstSerializer.compileNode (file:///Users/zachleat/Code/webc/src/ast.js:1154:36)
```

```
[11ty] Original error stack trace: evalmachine.<anonymous>:1
[11ty] class
[11ty]      
[11ty] 
[11ty] SyntaxError: Unexpected end of input
[11ty]     at new Script (node:vm:100:7)
[11ty]     at createScript (node:vm:257:10)
[11ty]     at Object.runInNewContext (node:vm:298:10)
[11ty]     at Function.evaluateAttribute (file:///Users/zachleat/Code/webc/src/moduleScript.js:26:13)
[11ty]     at Function.normalizeAttribute (file:///Users/zachleat/Code/webc/src/attributeSerializer.js:67:39)
[11ty]     at Function.getString (file:///Users/zachleat/Code/webc/src/attributeSerializer.js:101:50)
[11ty]     at AstSerializer.renderStartTag (file:///Users/zachleat/Code/webc/src/ast.js:646:56)
[11ty]     at AstSerializer.compileNode (file:///Users/zachleat/Code/webc/src/ast.js:1051:56)
[11ty]     at AstSerializer.getChildContent (file:///Users/zachleat/Code/webc/src/ast.js:544:40)
[11ty]     at async AstSerializer.compileNode (file:///Users/zachleat/Code/webc/src/ast.js:1154:36)
```

**Comment by kleinfreund** [comment]
What's the template for this look like?

**Comment by zachleat** [comment]
in the component file I was seeing errors for `class="`toggle${class ? ` ${class}`: ''}`"` and `class="class"` respectively

**Comment by kleinfreund** [comment]
Oh, right, `class` might *perhaps* be a reserved keyword in JavaScript, eh? 😅

**Comment by zachleat** [comment]
Ahahahaha welllllll 😅

**Comment by zachleat** [comment]
This is now an improved error messaging issue 😅 and will ship with the next version

**Comment by zachleat** [comment]
hahaha officially the ability to use `class` as a variable in JS feels a bit different than an ability to use `class` as an attribute in your markup but unofficially _no comment_ 😅

**Comment by kleinfreund** [comment]
Hey I’m just being snarky and you know it _unofficially_
