### ISSUE TITLE
Cannot read properties of undefined (reading 'startLine')

### ISSUE THREAD

**Issue by andy-bond** [11ty/webc#67]
**Description**
While using WebC in 11ty with `eleventy-plugin-webc@0.6.0`, you get a TypeError that prevents 11ty from writing pages if your WebC layout/page has a tag that is a void element or self closing. 

I could not get this error to reproduce in the WebC test repository but I believe this can be confirmed by checking how Parse5 parses void elements - [prepared snippet in the Parse5 playground](https://astexplorer.net/#/gist/f38943d7ef8a5e0a97089fbf9e78c210/737a7f4eb7eac23622029c37bed5ed7c306e8849).

You can see in the snippet if you expand the `sourceCodeLocation` of the `meta` tag that it does not contain an `endTag` object. This means that `let end = node.sourceCodeLocation.endTag;` will be `undefined` in those cases - resulting in `end.startLine` producing the error below.

**Debug Output**
```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble writing to "_site/test/index.html" from "./src/test.webc" (via EleventyTemplateError)
[11ty] 2. Cannot read properties of undefined (reading 'startLine') (via TypeError)
[11ty]
[11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'startLine')
[11ty]     at AstSerializer.getPreparsedRawTextContent (file:///C:/Users/andyb/Documents/Projects/andy.bond/node_modules/@11ty/webc/src/ast.js:1150:28)
[11ty]     at AstSerializer.transformContent (file:///C:/Users/andyb/Documents/Projects/andy.bond/node_modules/@11ty/webc/src/ast.js:778:29)
[11ty]     at AstSerializer.compileNode (file:///C:/Users/andyb/Documents/Projects/andy.bond/node_modules/@11ty/webc/src/ast.js:1199:20)
[11ty]     at AstSerializer.getChildContent (file:///C:/Users/andyb/Documents/Projects/andy.bond/node_modules/@11ty/webc/src/ast.js:635:40)
[11ty]     at AstSerializer.compileNode (file:///C:/Users/andyb/Documents/Projects/andy.bond/node_modules/@11ty/webc/src/ast.js:1319:46)
[11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11ty]     at async AstSerializer.getChildContent (file:///C:/Users/andyb/Documents/Projects/andy.bond/node_modules/@11ty/webc/src/ast.js:635:29)
[11ty]     at async AstSerializer.compileNode (file:///C:/Users/andyb/Documents/Projects/andy.bond/node_modules/@11ty/webc/src/ast.js:1358:36)
[11ty]     at async AstSerializer.getChildContent (file:///C:/Users/andyb/Documents/Projects/andy.bond/node_modules/@11ty/webc/src/ast.js:635:29)
[11ty]     at async AstSerializer.compileNode (file:///C:/Users/andyb/Documents/Projects/andy.bond/node_modules/@11ty/webc/src/ast.js:1358:36)
```

**Comment by zachleat** [comment]
Can you provide the full `<meta>` element input you’re parsing? I’m guessing this only applies when `webc:raw` is in play

**Comment by zachleat** [comment]
Just to be clear, this test passes fine with WebC 0.6:

```js
test("Using webc:raw on void elements #67", async t => {
	let component = new WebC();

	component.setContent(`<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
	<h1>My First Heading</h1>
	<p>My first paragraph.</p>
</body>
</html>`);

	let { html } = await component.compile();

	t.is(html, `<!doctype html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<h1>My First Heading</h1>
	<p>My first paragraph.</p>

</body>
</html>`);
});
```

so I’m trying to figure out how to make it fail!

**Comment by andy-bond** [comment]
Here is where I get the error - made a very small project to test this with.

**_layouts/base.webc**
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="generator" :content="eleventy.generator" />

    <meta webc:is="meta-social" />

    <style @html="getCss(page.url)"></style>
    <script @html="getJs(page.url)"></script>
  </head>
  <body>
    <template webc:nokeep @html="content"></template>
  </body>
</html>
```

**index.webc**
```html
---
layout: base
title: Test
---

<span>Test</span>
```

**_components/head/meta-social.webc**
```html
<script webc:type="render" webc:is="template">
  function () {
    const author = this.metadata.author;
  	const title = `${this.title} • ${author}`;
    const description = this.description ?? '';

    const opengraphFallbackImage = encodeURIComponent(`${this.metadata.url}/opengraph`);
    const opengraph = this.opengraphImageUrl ?? `${opengraphFallbackImage}/opengraph`;

  	return `
      <meta property="og:title" content="${title}">
  	  <meta name="description" property="og:description" content="${description}">
  	  <meta name="author" content="${author}">
      <meta property="og:type" content="website"/>
      <meta property="og:url" content="${this.page.url}"/>
      <meta property="og:image" content="${opengraph}"/>
     `;
  }
</script>
```

---

What's interesting is that this *doesn't* occur if I swap `<meta webc:is="meta-social" />` for `<meta webc:is="meta-favicons" />`

**_components/head/meta-favicons.webc**
```html
<link
  rel="apple-touch-icon"
  sizes="180x180"
  :href="url('/static/favicon/apple-touch-icon.png')"
/>
<link
  rel="icon"
  type="image/png"
  sizes="32x32"
  :href="url('/static/favicon/favicon-32x32.png')"
/>
<link
  rel="icon"
  type="image/png"
  sizes="16x16"
  :href="url('/static/favicon/favicon-16x16.png')"
/>
<link rel="manifest" :href="url('/static/favicon/site.webmanifest')" />
<meta name="apple-mobile-web-app-title" :content="this.metadata.name" />
<meta name="application-name" :content="this.metadata.name" />
<meta name="msapplication-TileColor" content="#15273d" />
<meta name="theme-color" content="#0d1b2a" />
```

**Comment by zachleat** [comment]
Regression from #61

**Comment by zachleat** [comment]
Shipping with v0.6.2, appreciate you!

I took a bit different approach from your PR—you can have a look here https://github.com/11ty/webc/commit/5a8224d0a8c0ff5f3409b46d6e876b0f5bff906f

**Comment by zachleat** [comment]
https://github.com/11ty/webc/releases/tag/v0.6.2 is out!
