### ISSUE TITLE
Vite dev and build modes having trouble with webc packaging

### ISSUE THREAD

**Issue by pauleveritt** [11ty/webc#81]
NodeJS 19, Vite 3.2.3. I'm using the Vite `vanilla` scaffold with most demo stuff removed. It has:

- `  "type": "module",` in `package.json`
- ` <script type="module" src="/main.js"></script>` in `index.html`
- A single line of `import { WebC } from "@11ty/webc";` in `main.js`

The dev server rendering in Chrome gives an exception:

```
Uncaught TypeError: require_path().posix is undefined
    js index.js:4
    __require2 @11ty_webc.js:16
    js pattern.js:5
    __require2 @11ty_webc.js:16
    js index.js:12
    __require2 @11ty_webc.js:16
    js tasks.js:4
    __require2 @11ty_webc.js:16
    js index.js:2
    __require2 @11ty_webc.js:16
    <anonymous> webc.js:2
index.js:4:23
```

This next one is likely for Rollup, not here, but nonetheless...the Vite `build` command logs this to the console:

```
vite v3.2.4 building for production...
✓ 369 modules transformed.
'createHash' is not exported by __vite-browser-external, imported by node_modules/@11ty/webc/src/ast.js
file: /Users/pauleveritt/WebstormProjects/webc_testing/node_modules/@11ty/webc/src/ast.js:4:9
2: import fs from "fs";
3: import os from "os";
4: import { createHash } from "crypto";
            ^
5: import { DepGraph } from "dependency-graph";
error during build:
Error: 'createHash' is not exported by __vite-browser-external, imported by node_modules/@11ty/webc/src/ast.js
    at error (file:///Users/pauleveritt/WebstormProjects/webc_testing/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///Users/pauleveritt/WebstormProjects/webc_testing/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
    at Module.traceVariable (file:///Users/pauleveritt/WebstormProjects/webc_testing/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///Users/pauleveritt/WebstormProjects/webc_testing/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at ChildScope.findVariable (file:///Users/pauleveritt/WebstormProjects/webc_testing/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ClassBodyScope.findVariable (file:///Users/pauleveritt/WebstormProjects/webc_testing/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///Users/pauleveritt/WebstormProjects/webc_testing/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at FunctionScope.findVariable (file:///Users/pauleveritt/WebstormProjects/webc_testing/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///Users/pauleveritt/WebstormProjects/webc_testing/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at Identifier.bind (file:///Users/pauleveritt/WebstormProjects/webc_testing/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
```

**Comment by zachleat** [comment]
Hmm… here’s what I see, looks like an incompatibility with `fast-glob` and Vite.

```
Module "path" has been externalized for browser compatibility. Cannot access "path.posix" in client code.
get @ browser-external:path:9
node_modules/glob-parent/index.js @ index.js:4
__require2 @ @11ty_webc.js?v=1a76a99b:16
node_modules/fast-glob/out/utils/pattern.js @ pattern.js:5
__require2 @ @11ty_webc.js?v=1a76a99b:16
node_modules/fast-glob/out/utils/index.js @ index.js:12
__require2 @ @11ty_webc.js?v=1a76a99b:16
node_modules/fast-glob/out/managers/tasks.js @ tasks.js:4
__require2 @ @11ty_webc.js?v=1a76a99b:16
node_modules/fast-glob/out/index.js @ index.js:2
__require2 @ @11ty_webc.js?v=1a76a99b:16
(anonymous) @ webc.js:2
index.js:4 Uncaught TypeError: Cannot read properties of undefined (reading 'dirname')
    at node_modules/glob-parent/index.js (index.js:4:40)
    at __require2 (@11ty_webc.js?v=1a76a99b:16:50)
    at node_modules/fast-glob/out/utils/pattern.js (pattern.js:5:20)
    at __require2 (@11ty_webc.js?v=1a76a99b:16:50)
    at node_modules/fast-glob/out/utils/index.js (index.js:12:17)
    at __require2 (@11ty_webc.js?v=1a76a99b:16:50)
    at node_modules/fast-glob/out/managers/tasks.js (tasks.js:4:15)
    at __require2 (@11ty_webc.js?v=1a76a99b:16:50)
    at node_modules/fast-glob/out/index.js (index.js:2:21)
    at __require2 (@11ty_webc.js?v=1a76a99b:16:50)
node_modules/glob-parent/index.js @ index.js:4
__require2 @ @11ty_webc.js?v=1a76a99b:16
node_modules/fast-glob/out/utils/pattern.js @ pattern.js:5
__require2 @ @11ty_webc.js?v=1a76a99b:16
node_modules/fast-glob/out/utils/index.js @ index.js:12
__require2 @ @11ty_webc.js?v=1a76a99b:16
node_modules/fast-glob/out/managers/tasks.js @ tasks.js:4
__require2 @ @11ty_webc.js?v=1a76a99b:16
node_modules/fast-glob/out/index.js @ index.js:2
__require2 @ @11ty_webc.js?v=1a76a99b:16
(anonymous) @ webc.js:2
```

Changing the test case to `import fastglob from "fast-glob";` instead of WebC gives back the same error. Is this a Vite incompatibility?

`fast-glob` should only be used with the WebC `defineComponents` method—we could dynamically import it? Hmm…

**Comment by zachleat** [comment]
Just to take a step back, this isn’t trying to bundle WebC to the client is it? This is using WebC ƒor server rendering?

**Comment by pauleveritt** [comment]
Correct. More specifically, I'm experimenting with a test-oriented development experience using Vitest. I have it working with Eleventy itself and `happy-dom`. Experimenting with removal of Eleventy and plugging the data cascade with something like µsignal.

**Comment by pauleveritt** [comment]
I will recreate a bug with just `fast-glob` and remove WebC. I'll then report to either `fast-glob` or throw it on the infinite pile at Vite.

Thus, closing this.

**Comment by zachleat** [comment]
I wouldn’t be opposed to a dynamic import on fast-glob, if that helps—but it’d probably be a lower priority task.

Regardless, thanks Paul!

**Comment by pauleveritt** [comment]
Let's leave this closed. I'll make a video series on this idea -- productive WebC development with Vitest -- but with 11ty. If it seems a useful idea, we can revisit directly-with-webc.

OT, I joined Mastodon last night, primarily because you stopped tweeting. 😀

**Comment by zachleat** [comment]
Awesome! What’s your profile? I think I missed it!

**Comment by pauleveritt** [comment]
When there's something worth your time to look at, I'll give you a nudge. 😇
